all:
  hosts:
    node1:
      ansible_host: 192.168.64.2
      ansible_user: user
    node2:
      ansible_host: 192.168.64.3
      ansible_user: user
managers:
  hosts:
    node1:
workers:
  hosts:
    node2:
