---
- name: Prepare nodes
  hosts: workers
  roles:
    - { role: bootstrap-python }
    - { role: prepare-node }
- name: Join to Docker Swarm as worker
  hosts: workers
  tasks:
    - community.docker.docker_swarm:
        state: join
        remote_addrs: [
          "{{ hostvars[groups['managers'][0]].ansible_host }}:2377"
        ]
        join_token: "{{ joinToken.worker }}"
