---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
- import_tasks: docker.yml
- ansible.builtin.yum:
    name:
      - python3-pip
- ansible.builtin.pip:
    name:
      - docker
